version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps: 
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules
  push-image:
    machine: true
    steps:
      - checkout
      - run: echo ${google_auth} > ${HOME}/gcp-key.json
      - run: docker build --rm=false -t gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud docker -- push gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1